allowBuilds:
  '@prisma/engines': false
  esbuild: false
  msgpackr-extract: set this to true or false
  prisma: false
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - shadcn@4.16.1
  - react-hook-form@7.84.0
